openapi: 3.0.0
info:
  title: chronicles-api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /chronicle/create:
    post:
      summary: Chronicle object
      tags:
        - Chronicles
        - timeline
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/chronicles.v1.yaml
        description: Instance de Chronique
    parameters: []
components:
  schemas: {}
